import PouchDB from './pouchdb-core.js';
export { default } from './pouchdb-core.js';
import IDBPouch from './pouchdb-adapter-idb.js';
import mapreduce from './pouchdb-mapreduce.js';
import { r as replication } from './index-cb44dfd9.js';
import 'node:events';
import './upsert-bb51d1b8.js';
import 'stream';
import 'http';
import 'url';
import './abort-controller-08d1ea45.js';
import 'punycode';
import './_commonjsHelpers-24198af3.js';
import 'util';
import 'https';
import 'zlib';
import './v4-b7ee9c0c.js';
import './pick-60e95b5a.js';
import './nextTick-ea093886.js';
import './clone-9d9f421b.js';
import './index-15c7260a.js';
import 'buffer';
import './functionName-97119de9.js';
import './guardedConsole-f54e5a40.js';
import './rev-75d26c01.js';
import 'crypto';
import './isRemote-2533b7cb.js';
import './once-de8350b9.js';
import './collectConflicts-ad0b7c70.js';
import './rootToLeaf-f8d0e78a.js';
import './isLocalId-d067de54.js';
import './findPathToLeaf-7e69c93c.js';
import 'pouchdb-utils.js';
import './pouchdb-changes-filter.js';
import './normalizeDdocFunctionName-ea3481cf.js';
import './matches-selector-e1c3dac5.js';
import './index-7f131e04.js';
import 'vm';
import './index-f8a9e0ec.js';
import './latest-0521537f.js';
import './binaryStringToBlobOrBuffer-3ba36433.js';
import './typedBuffer-a8220a49.js';
import './preprocessAttachments-db47f8d6.js';
import './binaryMd5-601b2421.js';
import './processDocs-62433f84.js';
import './merge-1e46cced.js';
import './revExists-12209d1c.js';
import './safeJsonStringify-6520e306.js';
import './base64StringToBlobOrBuffer-3fd03be6.js';
import './readAsBinaryString-06e911ba.js';
import './changesHandler-c020580c.js';
import './filterChange-0090dde4.js';
import './toPromise-05472f25.js';
import './index-bd745a58.js';
import './flatten-994f45c6.js';
import './pouchdb-crypto.js';
import './pouchdb-checkpointer.js';
import './pouchdb-generate-replication-id.js';

PouchDB.plugin(IDBPouch)
  //.plugin(HttpPouch)
  .plugin(mapreduce)
  .plugin(replication);
