import PouchDB from './pouchdb-core.js';
export { default } from './pouchdb-core.js';
import IDBPouch from './pouchdb-adapter-idb.js';
import mapreduce from './pouchdb-mapreduce.js';
import replication from './pouchdb-replication.js';
import 'node:events';
import './fetch-f2310cb2.js';
import 'stream';
import 'http';
import 'url';
import 'punycode';
import 'https';
import 'zlib';
import './_commonjsHelpers-24198af3.js';
import 'util';
import './rev-48662a2a.js';
import './pouchdb-errors.js';
import 'crypto';
import './stringMd5-15f53eba.js';
import './nextTick-ea093886.js';
import './clone-7eeb6295.js';
import './functionName-706c6c65.js';
import 'buffer';
import './guardedConsole-f54e5a40.js';
import './isRemote-2533b7cb.js';
import './upsert-331b6913.js';
import './once-de8350b9.js';
import './collectConflicts-ad0b7c70.js';
import './rootToLeaf-f8d0e78a.js';
import './isLocalId-d067de54.js';
import './pouchdb-platform.js';
import 'node:assert';
import 'node:fs';
import 'node:buffer';
import 'node:crypto';
import 'node:stream';
import 'node:http';
import 'node:url';
import 'node:https';
import 'node:zlib';
import 'node:util';
import 'node:vm';
import 'node:path';
import 'node:os';
import './findPathToLeaf-7e69c93c.js';
import 'pouchdb-utils.js';
import './pouchdb-changes-filter.js';
import './normalizeDdocFunctionName-ea3481cf.js';
import './matches-selector-87ab4d5f.js';
import './pouchdb-collate.js';
import 'vm';
import './pouchdb-utils.js';
import './flatten-994f45c6.js';
import './scopeEval-ff3a416d.js';
import './toPromise-f6e385ee.js';
import './latest-0521537f.js';
import './parseDoc-71681539.js';
import './preprocessAttachments-0457f2a2.js';
import './binaryStringToBlobOrBuffer-39ece35b.js';
import './typedBuffer-a8220a49.js';
import './blobOrBufferToBinaryString-56930128.js';
import './binaryMd5-601b2421.js';
import './processDocs-7c802567.js';
import './merge-1e46cced.js';
import './revExists-12209d1c.js';
import './safeJsonStringify-6520e306.js';
import './base64StringToBlobOrBuffer-3fd03be6.js';
import './readAsBinaryString-06e911ba.js';
import './pouchdb-mapreduce-utils.js';
import './pouchdb-abstract-mapreduce.js';
import './pouchdb-crypto.js';
import './pouchdb-checkpointer.js';
import './pouchdb-generate-replication-id.js';

PouchDB.plugin(IDBPouch)
  //.plugin(HttpPouch)
  .plugin(mapreduce)
  .plugin(replication);
