import PouchDB from './pouchdb-core.js';
export { default } from './pouchdb-core.js';
import IDBPouch from './pouchdb-adapter-idb.js';
import mapreduce from './pouchdb-mapreduce.js';
import replication from './pouchdb-replication.js';
import 'node:events';
import './fetch-ad491323.js';
import 'stream';
import 'http';
import 'url';
import 'punycode';
import 'https';
import 'zlib';
import 'fetch-cookie';
import './functionName-56a2e70f.js';
import 'crypto';
import './rev-591f7bff.js';
import './pouchdb-errors.js';
import './stringMd5-15f53eba.js';
import './nextTick-ea093886.js';
import './clone-3530a126.js';
import 'clone-buffer';
import './guardedConsole-f54e5a40.js';
import './isRemote-2533b7cb.js';
import './upsert-331b6913.js';
import './once-de8350b9.js';
import './collectConflicts-ad0b7c70.js';
import './rootToLeaf-f8d0e78a.js';
import './isLocalId-d067de54.js';
import './findPathToLeaf-7e69c93c.js';
import 'pouchdb-utils.js';
import './pouchdb-changes-filter.js';
import './normalizeDdocFunctionName-ea3481cf.js';
import './matches-selector-02a28973.js';
import './index-7f131e04.js';
import 'vm';
import './pouchdb-utils.js';
import './flatten-994f45c6.js';
import './scopeEval-ff3a416d.js';
import './toPromise-42fa3440.js';
import './latest-0521537f.js';
import './parseDoc-a0994e12.js';
import './preprocessAttachments-0457f2a2.js';
import './binaryStringToBlobOrBuffer-39ece35b.js';
import './typedBuffer-a8220a49.js';
import './blobOrBufferToBinaryString-56930128.js';
import './binaryMd5-601b2421.js';
import './processDocs-2980e64a.js';
import './merge-1e46cced.js';
import './revExists-12209d1c.js';
import './safeJsonStringify-a65d9a0c.js';
import 'vuvuzela';
import './base64StringToBlobOrBuffer-3fd03be6.js';
import './readAsBinaryString-06e911ba.js';
import './pouchdb-mapreduce-utils.js';
import './pouchdb-abstract-mapreduce.js';
import './pouchdb-crypto.js';
import './pouchdb-checkpointer.js';
import './pouchdb-generate-replication-id.js';

PouchDB.plugin(IDBPouch)
  //.plugin(HttpPouch)
  .plugin(mapreduce)
  .plugin(replication);
