import './pouchdb-browser.browser.js';
import PouchDB from './pouchdb-core.browser.js';
import './pouchdb-adapter-idb.browser.js';
import './pouchdb-utils.browser.js';
import './bulkGetShim-d4877145.js';
import './toPromise-9dada06a.js';
import './clone-abfcddc8.js';
import './functionName-9335a350.js';
import './_commonjsHelpers-24198af3.js';
import './__node-resolve_empty-5ffda92e.js';
import './guardedConsole-f54e5a40.js';
import './explainError-browser-c025e6c9.js';
import './parseUri-b061a2c5.js';
import './pouchdb-errors.browser.js';
import './flatten-994f45c6.js';
import './rev-5645662a.js';
import './spark-md5-2c57e5fc.js';
import './stringMd5-browser-5aecd2bd.js';
import './isRemote-f9121da9.js';
import './normalizeDdocFunctionName-ea3481cf.js';
import './scopeEval-ff3a416d.js';
import './upsert-331b6913.js';
import './rootToLeaf-f8d0e78a.js';
import './isLocalId-d067de54.js';
import './latest-0521537f.js';
import './parseDoc-5d2a34bd.js';
import './preprocessAttachments-1767f4bd.js';
import './base64-browser-5f7b6479.js';
import './binaryStringToBlobOrBuffer-browser-7dc25c1d.js';
import './blobOrBufferToBase64-browser-cd22f32f.js';
import './readAsBinaryString-06e911ba.js';
import './binaryMd5-browser-ad85bb67.js';
import './readAsArrayBuffer-625b2d33.js';
import './processDocs-7ad6f99c.js';
import './merge-7299d068.js';
import './revExists-12209d1c.js';
import './base64StringToBlobOrBuffer-browser-ac90e85f.js';
import './pouchdb-json.browser.js';
import './collectConflicts-6afe46fc.js';
import './pouchdb-adapter-http.browser.js';
import './pouchdb-fetch.browser.js';
import './pouchdb-mapreduce.browser.js';
import './pouchdb-mapreduce-utils.browser.js';
import './pouchdb-abstract-mapreduce.browser.js';
import './index-3a476dad.js';
import './pouchdb-replication.browser.js';
import './pouchdb-checkpointer.browser.js';
import './pouchdb-generate-replication-id.browser.js';
import 'node:events';
import './findPathToLeaf-7e69c93c.js';
import './pouchdb-changes-filter.browser.js';
import './pouchdb-selector-core.browser.js';



export { PouchDB as default };
