export { c as collectConflicts, a as collectLeaves } from './collectConflicts-6afe46fc.js';
export { c as compactTree, l as latest } from './latest-0521537f.js';
export { f as findPathToLeaf } from './findPathToLeaf-7e69c93c.js';
export { m as merge } from './merge-7299d068.js';
export { r as removeLeafFromTree } from './removeLeafFromTree-1fae4da6.js';
export { r as revExists } from './revExists-12209d1c.js';
export { r as rootToLeaf, t as traverseRevTree, w as winningRev } from './rootToLeaf-f8d0e78a.js';
export { i as isDeleted, a as isLocalId } from './isLocalId-d067de54.js';
import './clone-7eeb6295.js';
import './functionName-706c6c65.js';
import './_commonjsHelpers-24198af3.js';
import 'buffer';
import 'node:events';
import './pouchdb-errors.js';
import 'crypto';
