import PouchDB from './pouchdb-core.js';
import IDBPouch from './pouchdb-adapter-idb.js';
import HttpPouch from './pouchdb-adapter-http.js';
import mapreduce from './pouchdb-mapreduce.js';
import replication from './pouchdb-replication.js';
import './bulkGetShim-df36314d.js';
import './toPromise-1031f2f4.js';
import './clone-7eeb6295.js';
import './functionName-706c6c65.js';
import './_commonjsHelpers-24198af3.js';
import 'buffer';
import 'node:events';
import './nextTick-ea093886.js';
import './guardedConsole-f54e5a40.js';
import './pouchdb-errors.js';
import './rev-fc9bde4f.js';
import 'crypto';
import './stringMd5-15f53eba.js';
import './isRemote-f9121da9.js';
import './upsert-331b6913.js';
import './collectConflicts-6afe46fc.js';
import './rootToLeaf-f8d0e78a.js';
import './isLocalId-d067de54.js';
import './findPathToLeaf-7e69c93c.js';
import './pouchdb-fetch.js';
import 'stream';
import 'http';
import 'url';
import 'punycode';
import 'https';
import 'zlib';
import 'util';
import './pouchdb-changes-filter.js';
import './normalizeDdocFunctionName-ea3481cf.js';
import './pouchdb-selector-core.js';
import './index-3a476dad.js';
import 'vm';
import './pouchdb-utils.js';
import './parseUri-6d6043cb.js';
import './flatten-994f45c6.js';
import './scopeEval-ff3a416d.js';
import './latest-0521537f.js';
import './parseDoc-4c54e1d0.js';
import './preprocessAttachments-6ee037bd.js';
import './binaryStringToBlobOrBuffer-39ece35b.js';
import './typedBuffer-a8220a49.js';
import './blobOrBufferToBase64-e67e02aa.js';
import './blobOrBufferToBinaryString-26d9e545.js';
import './binaryMd5-601b2421.js';
import './processDocs-3dd3facd.js';
import './merge-7299d068.js';
import './revExists-12209d1c.js';
import './pouchdb-json.js';
import './base64StringToBlobOrBuffer-3fd03be6.js';
import './readAsBinaryString-06e911ba.js';
import './pouchdb-crypto.js';
import './pouchdb-mapreduce-utils.js';
import './pouchdb-abstract-mapreduce.js';
import './pouchdb-checkpointer.js';
import './pouchdb-generate-replication-id.js';

PouchDB.plugin(IDBPouch)
  .plugin(HttpPouch)
  .plugin(mapreduce)
  .plugin(replication);

export { PouchDB as default };
