import PouchDB from './pouchdb-core.js';
import LevelPouch from './pouchdb-adapter-leveldb.js';
import HttpPouch from './pouchdb-adapter-http.js';
import mapreduce from './pouchdb-mapreduce.js';
import replication from './pouchdb-replication.js';
import './bulkGetShim-df36314d.js';
import './toPromise-1031f2f4.js';
import './clone-7eeb6295.js';
import './functionName-706c6c65.js';
import './_commonjsHelpers-24198af3.js';
import 'buffer';
import 'events';
import './nextTick-ea093886.js';
import './isRemote-d6980e06.js';
import './pouchdb-errors.js';
import './rev-a9160aa4.js';
import 'crypto';
import './stringMd5-15f53eba.js';
import './upsert-331b6913.js';
import './collectConflicts-6afe46fc.js';
import './rootToLeaf-f8d0e78a.js';
import './isLocalId-d067de54.js';
import 'node:events';
import './findPathToLeaf-7e69c93c.js';
import './pouchdb-fetch.js';
import 'stream';
import 'http';
import 'url';
import 'punycode';
import 'https';
import 'zlib';
import 'util';
import './pouchdb-changes-filter.js';
import './normalizeDdocFunctionName-ea3481cf.js';
import './pouchdb-selector-core.js';
import './index-3a476dad.js';
import 'vm';
import './index-29ccb5c0.js';
import './index-65c4ad7e.js';
import 'assert';
import './pouchdb-utils.js';
import './parseUri-6d6043cb.js';
import './flatten-994f45c6.js';
import './scopeEval-ff3a416d.js';
import './allDocsKeysQuery-9ff66512.js';
import './parseDoc-89319fc2.js';
import './latest-0521537f.js';
import './binaryStringToBlobOrBuffer-85a41a32.js';
import './typedBuffer-a8220a49.js';
import './binaryMd5-601b2421.js';
import './processDocs-87c36f74.js';
import './merge-7299d068.js';
import './revExists-12209d1c.js';
import './pouchdb-json.js';
import 'node:fs';
import 'path';
import 'fs';
import 'os';
import 'node:stream';
import './base64StringToBlobOrBuffer-3fd03be6.js';
import './blobOrBufferToBase64-e67e02aa.js';
import './pouchdb-mapreduce-utils.js';
import './pouchdb-abstract-mapreduce.js';
import './pouchdb-checkpointer.js';
import './pouchdb-generate-replication-id.js';

PouchDB.plugin(LevelPouch)
  .plugin(HttpPouch)
  .plugin(mapreduce)
  .plugin(replication);

export { PouchDB as default };
