import './pouchdb-browser.browser.js';
import PouchDB from './pouchdb-core.browser.js';
import './pouchdb-adapter-idb.browser.js';
import './pouchdb-utils.browser.js';
import './bulkGetShim-75479c95.js';
import './toPromise-06b5d6a8.js';
import './clone-f35bcc51.js';
import './functionName-4d6db487.js';
import './_commonjsHelpers-24198af3.js';
import './__node-resolve_empty-b1d43ca8.js';
import 'node:events';
import './guardedConsole-f54e5a40.js';
import './explainError-browser-c025e6c9.js';
import './parseUri-b061a2c5.js';
import './pouchdb-errors.browser.js';
import './flatten-994f45c6.js';
import './rev-d51344b8.js';
import './spark-md5-2c57e5fc.js';
import './stringMd5-browser-5aecd2bd.js';
import './isRemote-f9121da9.js';
import './normalizeDdocFunctionName-ea3481cf.js';
import './scopeEval-ff3a416d.js';
import './upsert-331b6913.js';
import './rootToLeaf-f8d0e78a.js';
import './isLocalId-d067de54.js';
import './latest-0521537f.js';
import './parseDoc-e17a8c17.js';
import './preprocessAttachments-af601f94.js';
import './binaryStringToBlobOrBuffer-browser-2c8e268c.js';
import './blobOrBufferToBase64-browser-35d54d5e.js';
import './readAsBinaryString-06e911ba.js';
import './binaryMd5-browser-ff2f482d.js';
import './readAsArrayBuffer-625b2d33.js';
import './processDocs-e4ed6d00.js';
import './merge-7299d068.js';
import './revExists-12209d1c.js';
import './base64StringToBlobOrBuffer-browser-ee4c0b54.js';
import './pouchdb-json.browser.js';
import './collectConflicts-6afe46fc.js';
import './pouchdb-adapter-http.browser.js';
import './pouchdb-crypto.browser.js';
import './pouchdb-fetch.browser.js';
import './pouchdb-mapreduce.browser.js';
import './pouchdb-mapreduce-utils.browser.js';
import './pouchdb-abstract-mapreduce.browser.js';
import './index-3a476dad.js';
import './pouchdb-replication.browser.js';
import './pouchdb-checkpointer.browser.js';
import './pouchdb-generate-replication-id.browser.js';
import './findPathToLeaf-7e69c93c.js';
import './pouchdb-changes-filter.browser.js';
import './pouchdb-selector-core.browser.js';



export { PouchDB as default };
