name: Install dependencies
description: Install npm dependencies from package.json

inputs:
  node-version:
    description: Specify the Node.js version to install
    required: true

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install
      shell: bash
